import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
// import { PageLayout } from "~/components/layout";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

const CreateObjectWizard = () => {
  const { user } = useUser();

  // console.log(user);

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <Image
        src={user.profileImageUrl}
        alt="Profile image"
        className="h-10 w-10 rounded-full"
        width={56}
        height={56}
      />
      <input
        placeholder="Type some text"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

// type ObjectWithUser = RouterOutputs["objects"]["getAll"][number];
// const CanvasContainer = (props: { object: ObjectWithUser }) => {};

// type ObjectWithUser = RouterOutputs["objects"]["getAll"][number];
// const CanvasContainer = (props: ObjectWithUser) => {
//   const {object, author} = props;
// };

type ObjectWithUser = RouterOutputs["objects"]["getAll"][number];
const CanvasContainer = (props: ObjectWithUser) => {
  const { object, author } = props;
  return (
    <div key={object.id} className="flex gap-2 p-2">
      <span>{object.objectType}</span>
      <div className="flex items-center gap-1 rounded-md bg-zinc-700 p-1">
        <Image
          src={author.profileImageUrl}
          className="h-7 w-7 rounded-full"
          alt={`@${author.username}'s profile pic`}
          width={56}
          height={56}
        />
        <div className="flex flex-col text-xs font-bold text-slate-300">
          <span>{`@${author.username}`}</span>
          <span className="flex justify-center font-thin">{`${dayjs(
            object.createdAt
          ).fromNow()}`}</span>
        </div>
      </div>
    </div>
  );
};

const Sandbox: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.objects.getAll.useQuery();

  // if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Sandbox</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/alphabet.svg" />
      </Head>
      {/* <PageLayout></PageLayout> */}
      <div className="h-full w-full md:max-w-7xl">
        <div className="flex border-b border-slate-400 p-4">
          {!user.isSignedIn && (
            <div className="flex justify-center">
              <SignInButton />
            </div>
          )}
          {!!user.isSignedIn && (
            <div className="flex justify-center">
              <CreateObjectWizard />
              <SignOutButton />
            </div>
          )}
        </div>
        <div>
          {data?.map((objectData) => (
            <CanvasContainer {...objectData} key={objectData.object.id} />
          ))}
        </div>
      </div>
    </>
  );
};

export default Sandbox;
