import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  const { data } = api.objects.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Next.js, Three.js Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/alphabet.svg" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <div>
          {data?.map((object) => (
            <div key={object.id}>{object.objectType}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
